name: ci-minio
on: workflow_dispatch

jobs:
  publish:
    name: Build and publish Docker image
    environment: build
    steps:

      - uses: actions/checkout@v2

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build
        run: |
          docker build -t ci-minio ci-minio/.

      - name: Print image name
        run: |
          echo ghcr.io/novelai/ci-minio:${GITHUB_SHA::7}

      - name: Push image
        run: |
          docker tag ci-minio ghcr.io/novelai/ci-minio:${GITHUB_SHA::7}
          docker push ghcr.io/novelai/ci-minio:${GITHUB_SHA::7}
